[package]
name = "contgrep"
version = "0.1.0"
authors = ["Angelos Oikonomopoulos <a.oikonomopoulos@vu.nl>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
env_logger = "0.6.0"
log = "0.4.6"
regex = "1.1.2"
